apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap.doge
  namespace: bot
data:
  BASE_VNT_QUANTITY: "300000"
  RANDOM_VNT_QUANTITY: "70000"
  FIAHUB_EMAIL: trdainhan@gmail.com
  MIN_USDT_FUND: "2"
  MAX_USDT_FUND: "60000"
  EXCHANGE_CLIENT: FTX
  RESET_ALL_ORDER_PERIOD: "6220800" # Cancel all, in seconds
