apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap.bot
  namespace: bot
data:
  REDIS_URL: redis-coingiatot-prod-master.redis-prod:6379
  REDIS_DB_NUMBER: "1"
  BINANCE_URL: https://api.binance.com
  FTX_URL: https://ftx.com
  EXCHANGE_CLIENT: BINANCE
  CHAT_ID: "-542148110"
  CHAT_ERROR_ID: "-527003097"
  TELEGRAM_HANDLER: "@tdnhan"
  MIN_USDT_FUND: "100"
  MAX_USDT_FUND: "2000"
  BASE_QUANTITY: "1"
  VALIDATE_FUND_PERIOD: "120"
  GET_NEW_PRICE_PERIOD: "60"
  JUMP_PERCENTAGE: "1"
